-- 1. Очистка (удаляем таблицы в обратном порядке зависимостей)
DROP TABLE IF EXISTS "AnalyticsReports";
DROP TABLE IF EXISTS "GoalDeposits";
DROP TABLE IF EXISTS "Goals";
DROP TABLE IF EXISTS "GoalCategories";
DROP TABLE IF EXISTS "__EFMigrationsHistory";
-- Удаляем историю миграций EF, если была
-- 2. Создание таблиц
-- Категории
CREATE TABLE "GoalCategories" (
    "CategoryId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "Icon" character varying(20) NOT NULL,
    "Color" character varying(7) NOT NULL,
    "SortOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_GoalCategories" PRIMARY KEY ("CategoryId")
);
-- Цели
CREATE TABLE "Goals" (
    "GoalId" integer GENERATED BY DEFAULT AS IDENTITY,
    "CategoryId" integer NOT NULL,
    "Title" character varying(100) NOT NULL,
    "TargetAmount" numeric(15, 2) NOT NULL,
    "CurrentAmount" numeric(15, 2) NOT NULL DEFAULT 0.0,
    "StartDate" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "EndDate" timestamp without time zone NOT NULL,
    "ImagePath" character varying(255),
    "Description" character varying(500),
    "Priority" integer NOT NULL DEFAULT 2,
    "IsCompleted" boolean NOT NULL DEFAULT FALSE,
    "CreatedAt" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_Goals" PRIMARY KEY ("GoalId"),
    CONSTRAINT "FK_Goals_GoalCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "GoalCategories" ("CategoryId") ON DELETE CASCADE,
    CONSTRAINT "CK_Goals_TargetAmount" CHECK ("TargetAmount" > 0),
    CONSTRAINT "CK_Goals_CurrentAmount" CHECK ("CurrentAmount" >= 0),
    CONSTRAINT "CK_Goals_Amounts" CHECK ("CurrentAmount" <= "TargetAmount"),
    CONSTRAINT "CK_Goals_Priority" CHECK ("Priority" IN (1, 2, 3))
);
-- Пополнения
CREATE TABLE "GoalDeposits" (
    "DepositId" integer GENERATED BY DEFAULT AS IDENTITY,
    "GoalId" integer NOT NULL,
    "Amount" numeric(15, 2) NOT NULL,
    "DepositDate" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "Comment" character varying(200),
    "DepositType" character varying(20) NOT NULL DEFAULT 'regular',
    CONSTRAINT "PK_GoalDeposits" PRIMARY KEY ("DepositId"),
    CONSTRAINT "FK_GoalDeposits_Goals_GoalId" FOREIGN KEY ("GoalId") REFERENCES "Goals" ("GoalId") ON DELETE CASCADE,
    CONSTRAINT "CK_GoalDeposits_Amount" CHECK ("Amount" > 0),
    CONSTRAINT "CK_GoalDeposits_Type" CHECK (
        "DepositType" IN (
            'regular',
            'salary',
            'freelance',
            'bonus',
            'other'
        )
    )
);
-- Отчеты
CREATE TABLE "AnalyticsReports" (
    "ReportId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReportType" character varying(20) NOT NULL DEFAULT 'monthly',
    "ReportDate" timestamp without time zone NOT NULL,
    "TotalGoals" integer NOT NULL,
    "CompletedGoals" integer NOT NULL,
    "TotalTargetAmount" numeric(15, 2) NOT NULL DEFAULT 0.0,
    "TotalCurrentAmount" numeric(15, 2) NOT NULL DEFAULT 0.0,
    "AverageProgress" numeric(5, 2) NOT NULL DEFAULT 0.0,
    "GeneratedAt" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_AnalyticsReports" PRIMARY KEY ("ReportId"),
    CONSTRAINT "CK_Reports_Type" CHECK (
        "ReportType" IN ('monthly', 'quarterly', 'yearly', 'custom')
    ),
    CONSTRAINT "CK_Reports_Goals" CHECK ("TotalGoals" >= "CompletedGoals"),
    CONSTRAINT "CK_Reports_Progress" CHECK (
        "AverageProgress" >= 0
        AND "AverageProgress" <= 100
    )
);
- - Индексы (для скорости) CREATE INDEX "IX_Goals_CategoryId" ON "Goals" ("CategoryId");
CREATE INDEX "IX_GoalDeposits_GoalId" ON "GoalDeposits" ("GoalId");
-- 3. Наполнение данными (Seeding)
-- 1. КАТЕГОРИИ
INSERT INTO "GoalCategories" (
        "CategoryId",
        "Name",
        "Icon",
        "Color",
        "SortOrder",
        "IsActive",
        "CreatedAt"
    ) OVERRIDING SYSTEM VALUE
VALUES (
        1,
        'Техника',
        '📱',
        '#311B92',
        1,
        true,
        CURRENT_TIMESTAMP
    ),
    (
        2,
        'Транспорт',
        '🚗',
        '#880E4F',
        2,
        true,
        CURRENT_TIMESTAMP
    ),
    (
        3,
        'Путешествия',
        '✈️',
        '#1A237E',
        3,
        true,
        CURRENT_TIMESTAMP
    ),
    (
        4,
        'Недвижимость',
        '🏠',
        '#B45309',
        4,
        true,
        CURRENT_TIMESTAMP
    ),
    (
        5,
        'Образование',
        '🎓',
        '#065F46',
        5,
        true,
        CURRENT_TIMESTAMP
    ),
    (
        6,
        'Здоровье',
        '🏥',
        '#EC4899',
        6,
        true,
        CURRENT_TIMESTAMP
    ),
    (
        7,
        'Развлечения',
        '🎮',
        '#8B5CF6',
        7,
        true,
        CURRENT_TIMESTAMP
    ),
    (
        8,
        'Другое',
        '⭐',
        '#6B7280',
        8,
        true,
        CURRENT_TIMESTAMP
    );
-- Обновляем счетчик ID для категорий
SELECT setval(
        pg_get_serial_sequence('"GoalCategories"', 'CategoryId'),
        8
    );
-- 2. ЦЕЛИ
INSERT INTO "Goals" (
        "GoalId",
        "CategoryId",
        "Title",
        "TargetAmount",
        "CurrentAmount",
        "StartDate",
        "EndDate",
        "Priority",
        "IsCompleted",
        "CreatedAt"
    ) OVERRIDING SYSTEM VALUE
VALUES (
        1,
        1,
        'IPHONE 15 PRO',
        120000,
        45000,
        CURRENT_DATE - INTERVAL '45 days',
        CURRENT_DATE + INTERVAL '45 days',
        2,
        FALSE,
        CURRENT_TIMESTAMP
    ),
    (
        2,
        3,
        'ПОЕЗДКА В ЯПОНИЮ',
        200000,
        62000,
        CURRENT_DATE - INTERVAL '120 days',
        CURRENT_DATE + INTERVAL '120 days',
        3,
        FALSE,
        CURRENT_TIMESTAMP
    ),
    (
        3,
        5,
        'МАГИСТРАТУРА',
        300000,
        90000,
        CURRENT_DATE - INTERVAL '180 days',
        CURRENT_DATE + INTERVAL '180 days',
        1,
        FALSE,
        CURRENT_TIMESTAMP
    ),
    (
        4,
        4,
        'Ремонт кухни',
        250000,
        25000,
        CURRENT_DATE - INTERVAL '10 days',
        CURRENT_DATE + INTERVAL '60 days',
        2,
        FALSE,
        CURRENT_TIMESTAMP
    ),
    (
        5,
        2,
        'Первый взнос',
        500000,
        75000,
        CURRENT_DATE - INTERVAL '200 days',
        CURRENT_DATE + INTERVAL '100 days',
        1,
        FALSE,
        CURRENT_TIMESTAMP
    ),
    (
        6,
        1,
        'Игровой ПК',
        150000,
        150000,
        CURRENT_DATE - INTERVAL '90 days',
        CURRENT_DATE - INTERVAL '5 days',
        1,
        TRUE,
        CURRENT_TIMESTAMP
    ),
    (
        7,
        6,
        'Лечение зубов',
        80000,
        10000,
        CURRENT_DATE - INTERVAL '5 days',
        CURRENT_DATE + INTERVAL '30 days',
        1,
        FALSE,
        CURRENT_TIMESTAMP
    ),
    (
        8,
        8,
        'Фин. подушка',
        100000,
        100000,
        CURRENT_DATE - INTERVAL '365 days',
        CURRENT_DATE - INTERVAL '30 days',
        3,
        TRUE,
        CURRENT_TIMESTAMP
    );
-- Обновляем счетчик ID для целей
SELECT setval(pg_get_serial_sequence('"Goals"', 'GoalId'), 8);
-- 3. ИСТОРИЯ ПОПОЛНЕНИЙ
INSERT INTO "GoalDeposits" (
        "GoalId",
        "Amount",
        "DepositDate",
        "Comment",
        "DepositType"
    )
VALUES (
        1,
        10000,
        CURRENT_DATE - INTERVAL '40 days',
        'Старт',
        'regular'
    ),
    (
        1,
        15000,
        CURRENT_DATE - INTERVAL '20 days',
        'Аванс',
        'salary'
    ),
    (
        1,
        20000,
        CURRENT_DATE - INTERVAL '5 days',
        'Подарок',
        'other'
    ),
    (
        2,
        30000,
        CURRENT_DATE - INTERVAL '100 days',
        'Отпускные',
        'bonus'
    ),
    (
        2,
        32000,
        CURRENT_DATE - INTERVAL '10 days',
        'Копилка',
        'regular'
    ),
    (
        3,
        45000,
        CURRENT_DATE - INTERVAL '150 days',
        'Семестр 1',
        'regular'
    ),
    (
        3,
        45000,
        CURRENT_DATE - INTERVAL '10 days',
        'Семестр 2',
        'regular'
    ),
    (
        5,
        75000,
        CURRENT_DATE - INTERVAL '190 days',
        'Продажа старой техники',
        'other'
    ),
    (
        6,
        50000,
        CURRENT_DATE - INTERVAL '80 days',
        'Начало',
        'regular'
    ),
    (
        6,
        100000,
        CURRENT_DATE - INTERVAL '10 days',
        'Премия годовая',
        'bonus'
    );
-- 4. АНАЛИТИЧЕСКИЕ ОТЧЕТЫ
INSERT INTO "AnalyticsReports" (
        "ReportType",
        "ReportDate",
        "TotalGoals",
        "CompletedGoals",
        "TotalTargetAmount",
        "TotalCurrentAmount",
        "AverageProgress",
        "GeneratedAt"
    )
VALUES (
        'monthly',
        CURRENT_DATE - INTERVAL '1 month',
        6,
        1,
        1200000,
        350000,
        29.5,
        CURRENT_TIMESTAMP - INTERVAL '1 month'
    ),
    (
        'monthly',
        CURRENT_DATE,
        8,
        2,
        1600000,
        557000,
        34.8,
        CURRENT_TIMESTAMP
    );