// <auto-generated />
using System;
using FinanceFlow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceFlow.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251116133913_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceFlow.Models.AnalyticsReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<decimal>("AverageProgress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("CompletedGoals")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalCurrentAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("TotalGoals")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalTargetAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("ReportId");

                    b.ToTable("AnalyticsReports", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reports_Goals", "\"TotalGoals\" >= \"CompletedGoals\"");

                            t.HasCheckConstraint("CK_Reports_Progress", "\"AverageProgress\" >= 0 AND \"AverageProgress\" <= 100");

                            t.HasCheckConstraint("CK_Reports_Type", "\"ReportType\" IN ('monthly', 'quarterly', 'yearly', 'custom')");
                        });
                });

            modelBuilder.Entity("FinanceFlow.Models.Goal", b =>
                {
                    b.Property<int>("GoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GoalId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("CurrentAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("GoalId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Goals", null, t =>
                        {
                            t.HasCheckConstraint("CK_Goals_Amounts", "\"CurrentAmount\" <= \"TargetAmount\"");

                            t.HasCheckConstraint("CK_Goals_CurrentAmount", "\"CurrentAmount\" >= 0");

                            t.HasCheckConstraint("CK_Goals_Dates", "\"EndDate\" > \"StartDate\"");

                            t.HasCheckConstraint("CK_Goals_Priority", "\"Priority\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_Goals_TargetAmount", "\"TargetAmount\" > 0");
                        });
                });

            modelBuilder.Entity("FinanceFlow.Models.GoalCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("CategoryId");

                    b.ToTable("GoalCategories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Color = "#8B5CF6",
                            CreatedAt = new DateTime(2025, 11, 16, 13, 39, 12, 845, DateTimeKind.Utc).AddTicks(3362),
                            Icon = "📱",
                            IsActive = true,
                            Name = "Техника",
                            SortOrder = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            Color = "#EF4444",
                            CreatedAt = new DateTime(2025, 11, 16, 13, 39, 12, 845, DateTimeKind.Utc).AddTicks(3364),
                            Icon = "🚗",
                            IsActive = true,
                            Name = "Авто",
                            SortOrder = 2
                        },
                        new
                        {
                            CategoryId = 3,
                            Color = "#10B981",
                            CreatedAt = new DateTime(2025, 11, 16, 13, 39, 12, 845, DateTimeKind.Utc).AddTicks(3365),
                            Icon = "✈️",
                            IsActive = true,
                            Name = "Путешествия",
                            SortOrder = 3
                        },
                        new
                        {
                            CategoryId = 4,
                            Color = "#F59E0B",
                            CreatedAt = new DateTime(2025, 11, 16, 13, 39, 12, 845, DateTimeKind.Utc).AddTicks(3366),
                            Icon = "🏠",
                            IsActive = true,
                            Name = "Недвижимость",
                            SortOrder = 4
                        },
                        new
                        {
                            CategoryId = 5,
                            Color = "#3B82F6",
                            CreatedAt = new DateTime(2025, 11, 16, 13, 39, 12, 845, DateTimeKind.Utc).AddTicks(3367),
                            Icon = "🎓",
                            IsActive = true,
                            Name = "Образование",
                            SortOrder = 5
                        },
                        new
                        {
                            CategoryId = 6,
                            Color = "#EC4899",
                            CreatedAt = new DateTime(2025, 11, 16, 13, 39, 12, 845, DateTimeKind.Utc).AddTicks(3369),
                            Icon = "🏥",
                            IsActive = true,
                            Name = "Здоровье",
                            SortOrder = 6
                        },
                        new
                        {
                            CategoryId = 7,
                            Color = "#8B5CF6",
                            CreatedAt = new DateTime(2025, 11, 16, 13, 39, 12, 845, DateTimeKind.Utc).AddTicks(3370),
                            Icon = "🎮",
                            IsActive = true,
                            Name = "Развлечения",
                            SortOrder = 7
                        },
                        new
                        {
                            CategoryId = 8,
                            Color = "#6B7280",
                            CreatedAt = new DateTime(2025, 11, 16, 13, 39, 12, 845, DateTimeKind.Utc).AddTicks(3371),
                            Icon = "⭐",
                            IsActive = true,
                            Name = "Другое",
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("FinanceFlow.Models.GoalDeposit", b =>
                {
                    b.Property<int>("DepositId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepositId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("DepositDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DepositType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("regular");

                    b.Property<int>("GoalId")
                        .HasColumnType("integer");

                    b.HasKey("DepositId");

                    b.HasIndex("GoalId");

                    b.ToTable("GoalDeposits", null, t =>
                        {
                            t.HasCheckConstraint("CK_GoalDeposits_Amount", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_GoalDeposits_Type", "\"DepositType\" IN ('regular', 'salary', 'freelance', 'bonus', 'other')");
                        });
                });

            modelBuilder.Entity("FinanceFlow.Models.Goal", b =>
                {
                    b.HasOne("FinanceFlow.Models.GoalCategory", "GoalCategory")
                        .WithMany("Goals")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoalCategory");
                });

            modelBuilder.Entity("FinanceFlow.Models.GoalDeposit", b =>
                {
                    b.HasOne("FinanceFlow.Models.Goal", "Goal")
                        .WithMany("Deposits")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("FinanceFlow.Models.Goal", b =>
                {
                    b.Navigation("Deposits");
                });

            modelBuilder.Entity("FinanceFlow.Models.GoalCategory", b =>
                {
                    b.Navigation("Goals");
                });
#pragma warning restore 612, 618
        }
    }
}
